<!-- Licensed under the PolyForm Noncommercial License 1.0.0 - see the LICENSE file in the project root for details. -->

<Project>
	<PropertyGroup>
		<PackageLicenseExpression>PolyForm-Noncommercial-1.0.0</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	</PropertyGroup>
</Project>
