// Licensed under the PolyForm Noncommercial License 1.0.0 - see the LICENSE file in the project root for details.

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporter.Core.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporter.Core.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category actions ähnelt.
        /// </summary>
        public static string ActionSheetTitleCategory {
            get {
                return ResourceManager.GetString("ActionSheetTitleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feed actions ähnelt.
        /// </summary>
        public static string ActionSheetTitleFeed {
            get {
                return ResourceManager.GetString("ActionSheetTitleFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        public static string ButtonFilter {
            get {
                return ResourceManager.GetString("ButtonFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string ButtonRefresh {
            get {
                return ResourceManager.GetString("ButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh all ähnelt.
        /// </summary>
        public static string ButtonRefreshAll {
            get {
                return ResourceManager.GetString("ButtonRefreshAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die — ähnelt.
        /// </summary>
        public static string CategoryNone {
            get {
                return ResourceManager.GetString("CategoryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All articles belonging to this feed will also be deleted. Continue? ähnelt.
        /// </summary>
        public static string ConfirmDeleteFeedMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteFeedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete feed? ähnelt.
        /// </summary>
        public static string ConfirmDeleteFeedTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A feed with this URL already exists. ähnelt.
        /// </summary>
        public static string ErrorFeedDuplicate {
            get {
                return ResourceManager.GetString("ErrorFeedDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a display title. ähnelt.
        /// </summary>
        public static string ErrorFeedTitleEmpty {
            get {
                return ResourceManager.GetString("ErrorFeedTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid feed URL. ähnelt.
        /// </summary>
        public static string ErrorFeedUrlInvalid {
            get {
                return ResourceManager.GetString("ErrorFeedUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string HealthStatusErrorLabel {
            get {
                return ResourceManager.GetString("HealthStatusErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string HealthStatusOkLabel {
            get {
                return ResourceManager.GetString("HealthStatusOkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string HealthStatusWarningLabel {
            get {
                return ResourceManager.GetString("HealthStatusWarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feeds ähnelt.
        /// </summary>
        public static string LabelCategoryFeedCount {
            get {
                return ResourceManager.GetString("LabelCategoryFeedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string LabelCategoryName {
            get {
                return ResourceManager.GetString("LabelCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string LabelFeedActions {
            get {
                return ResourceManager.GetString("LabelFeedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string LabelFeedCategory {
            get {
                return ResourceManager.GetString("LabelFeedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Health ähnelt.
        /// </summary>
        public static string LabelFeedHealthStatus {
            get {
                return ResourceManager.GetString("LabelFeedHealthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last check ähnelt.
        /// </summary>
        public static string LabelFeedLastCheck {
            get {
                return ResourceManager.GetString("LabelFeedLastCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string LabelFeedTitle {
            get {
                return ResourceManager.GetString("LabelFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unread ähnelt.
        /// </summary>
        public static string LabelFeedUnreadCount {
            get {
                return ResourceManager.GetString("LabelFeedUnreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No items ähnelt.
        /// </summary>
        public static string LabelNoItems {
            get {
                return ResourceManager.GetString("LabelNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        public static string PageTitleCategories {
            get {
                return ResourceManager.GetString("PageTitleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feeds ähnelt.
        /// </summary>
        public static string PageTitleFeeds {
            get {
                return ResourceManager.GetString("PageTitleFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Later ähnelt.
        /// </summary>
        public static string PageTitleLater {
            get {
                return ResourceManager.GetString("PageTitleLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unread ähnelt.
        /// </summary>
        public static string PageTitleUnread {
            get {
                return ResourceManager.GetString("PageTitleUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories will appear here. ähnelt.
        /// </summary>
        public static string PlaceholderCategories {
            get {
                return ResourceManager.GetString("PlaceholderCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feeds will appear here. ähnelt.
        /// </summary>
        public static string PlaceholderFeeds {
            get {
                return ResourceManager.GetString("PlaceholderFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display title ähnelt.
        /// </summary>
        public static string PlaceholderFeedTitle {
            get {
                return ResourceManager.GetString("PlaceholderFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Articles you save for later will appear here. ähnelt.
        /// </summary>
        public static string PlaceholderLater {
            get {
                return ResourceManager.GetString("PlaceholderLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings will appear here. ähnelt.
        /// </summary>
        public static string PlaceholderSettings {
            get {
                return ResourceManager.GetString("PlaceholderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unread articles will appear here. ähnelt.
        /// </summary>
        public static string PlaceholderUnread {
            get {
                return ResourceManager.GetString("PlaceholderUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronization failed. ähnelt.
        /// </summary>
        public static string SyncStatusError {
            get {
                return ResourceManager.GetString("SyncStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        public static string TabCategories {
            get {
                return ResourceManager.GetString("TabCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feeds ähnelt.
        /// </summary>
        public static string TabFeeds {
            get {
                return ResourceManager.GetString("TabFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Later ähnelt.
        /// </summary>
        public static string TabLater {
            get {
                return ResourceManager.GetString("TabLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unread ähnelt.
        /// </summary>
        public static string TabUnread {
            get {
                return ResourceManager.GetString("TabUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to Reporter. ähnelt.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Article actions ähnelt.
        /// </summary>
        public static string ActionSheetArticle {
            get {
                return ResourceManager.GetString("ActionSheetArticle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bookmark ähnelt.
        /// </summary>
        public static string ButtonBookmark {
            get {
                return ResourceManager.GetString("ButtonBookmark", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All read ähnelt.
        /// </summary>
        public static string ButtonMarkAllRead {
            get {
                return ResourceManager.GetString("ButtonMarkAllRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark as read ähnelt.
        /// </summary>
        public static string ButtonMarkAsRead {
            get {
                return ResourceManager.GetString("ButtonMarkAsRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pull down to refresh ähnelt.
        /// </summary>
        public static string LabelPullToRefresh {
            get {
                return ResourceManager.GetString("LabelPullToRefresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unread articles ähnelt.
        /// </summary>
        public static string LabelUnreadArticles {
            get {
                return ResourceManager.GetString("LabelUnreadArticles", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a keyword. ähnelt.
        /// </summary>
        public static string ErrorKeywordEmpty {
            get {
                return ResourceManager.GetString("ErrorKeywordEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This keyword already exists. ähnelt.
        /// </summary>
        public static string ErrorKeywordDuplicate {
            get {
                return ResourceManager.GetString("ErrorKeywordDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The keyword may be at most 500 characters long. ähnelt.
        /// </summary>
        public static string ErrorKeywordTooLong {
            get {
                return ResourceManager.GetString("ErrorKeywordTooLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic background refresh ähnelt.
        /// </summary>
        public static string SettingsAutoRefreshLabel {
            get {
                return ResourceManager.GetString("SettingsAutoRefreshLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Periodically load feeds in the background ähnelt.
        /// </summary>
        public static string SettingsAutoRefreshHint {
            get {
                return ResourceManager.GetString("SettingsAutoRefreshHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark as read automatically ähnelt.
        /// </summary>
        public static string SettingsAutoMarkReadLabel {
            get {
                return ResourceManager.GetString("SettingsAutoMarkReadLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When opening an article ähnelt.
        /// </summary>
        public static string SettingsAutoMarkReadHint {
            get {
                return ResourceManager.GetString("SettingsAutoMarkReadHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delay until marking ähnelt.
        /// </summary>
        public static string SettingsAutoMarkReadDelayLabel {
            get {
                return ResourceManager.GetString("SettingsAutoMarkReadDelayLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Immediately ähnelt.
        /// </summary>
        public static string SettingsDelayImmediate {
            get {
                return ResourceManager.GetString("SettingsDelayImmediate", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 second ähnelt.
        /// </summary>
        public static string SettingsDelay1s {
            get {
                return ResourceManager.GetString("SettingsDelay1s", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 seconds ähnelt.
        /// </summary>
        public static string SettingsDelay3s {
            get {
                return ResourceManager.GetString("SettingsDelay3s", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5 seconds ähnelt.
        /// </summary>
        public static string SettingsDelay5s {
            get {
                return ResourceManager.GetString("SettingsDelay5s", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every 15 minutes ähnelt.
        /// </summary>
        public static string SettingsInterval15Min {
            get {
                return ResourceManager.GetString("SettingsInterval15Min", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every 30 minutes ähnelt.
        /// </summary>
        public static string SettingsInterval30Min {
            get {
                return ResourceManager.GetString("SettingsInterval30Min", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hourly ähnelt.
        /// </summary>
        public static string SettingsIntervalHourly {
            get {
                return ResourceManager.GetString("SettingsIntervalHourly", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every 4 hours ähnelt.
        /// </summary>
        public static string SettingsInterval4Hours {
            get {
                return ResourceManager.GetString("SettingsInterval4Hours", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die + Add ähnelt.
        /// </summary>
        public static string SettingsKeywordAdd {
            get {
                return ResourceManager.GetString("SettingsKeywordAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partial match, case doesn't matter ähnelt.
        /// </summary>
        public static string SettingsKeywordMatchLabel {
            get {
                return ResourceManager.GetString("SettingsKeywordMatchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Also matches variants within words ähnelt.
        /// </summary>
        public static string SettingsKeywordMatchHint {
            get {
                return ResourceManager.GetString("SettingsKeywordMatchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always on ähnelt.
        /// </summary>
        public static string SettingsKeywordMatchStatus {
            get {
                return ResourceManager.GetString("SettingsKeywordMatchStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtered articles are deleted after the retention period based on their publication date. ähnelt.
        /// </summary>
        public static string SettingsKeywordInfo {
            get {
                return ResourceManager.GetString("SettingsKeywordInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter keyword… ähnelt.
        /// </summary>
        public static string SettingsKeywordPlaceholder {
            get {
                return ResourceManager.GetString("SettingsKeywordPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications ähnelt.
        /// </summary>
        public static string SettingsNotificationsLabel {
            get {
                return ResourceManager.GetString("SettingsNotificationsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get notified about new articles ähnelt.
        /// </summary>
        public static string SettingsNotificationsHint {
            get {
                return ResourceManager.GetString("SettingsNotificationsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quiet hours (do not disturb) ähnelt.
        /// </summary>
        public static string SettingsQuietHoursLabel {
            get {
                return ResourceManager.GetString("SettingsQuietHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No notifications during this period ähnelt.
        /// </summary>
        public static string SettingsQuietHoursHint {
            get {
                return ResourceManager.GetString("SettingsQuietHoursHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FROM ähnelt.
        /// </summary>
        public static string SettingsQuietHoursFrom {
            get {
                return ResourceManager.GetString("SettingsQuietHoursFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TO ähnelt.
        /// </summary>
        public static string SettingsQuietHoursTo {
            get {
                return ResourceManager.GetString("SettingsQuietHoursTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep read articles ähnelt.
        /// </summary>
        public static string SettingsRetentionLabel {
            get {
                return ResourceManager.GetString("SettingsRetentionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} days ähnelt.
        /// </summary>
        public static string SettingsRetentionDaysFormat {
            get {
                return ResourceManager.GetString("SettingsRetentionDaysFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unread articles and articles bookmarked via the "Later" tab are kept permanently. ähnelt.
        /// </summary>
        public static string SettingsRetentionInfo {
            get {
                return ResourceManager.GetString("SettingsRetentionInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 day – 90 days – 180 days – 365 days ähnelt.
        /// </summary>
        public static string SettingsRetentionDayMarks {
            get {
                return ResourceManager.GetString("SettingsRetentionDayMarks", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retention &amp; storage ähnelt.
        /// </summary>
        public static string SettingsSectionRetention {
            get {
                return ResourceManager.GetString("SettingsSectionRetention", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyword filter (blacklist) ähnelt.
        /// </summary>
        public static string SettingsSectionKeywords {
            get {
                return ResourceManager.GetString("SettingsSectionKeywords", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronization &amp; reading flow ähnelt.
        /// </summary>
        public static string SettingsSectionSync {
            get {
                return ResourceManager.GetString("SettingsSectionSync", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications &amp; quiet hours ähnelt.
        /// </summary>
        public static string SettingsSectionNotifications {
            get {
                return ResourceManager.GetString("SettingsSectionNotifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearance ähnelt.
        /// </summary>
        public static string SettingsSectionAppearance {
            get {
                return ResourceManager.GetString("SettingsSectionAppearance", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fetch interval ähnelt.
        /// </summary>
        public static string SettingsRefreshIntervalLabel {
            get {
                return ResourceManager.GetString("SettingsRefreshIntervalLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color scheme ähnelt.
        /// </summary>
        public static string SettingsThemeLabel {
            get {
                return ResourceManager.GetString("SettingsThemeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        public static string SettingsThemeSystem {
            get {
                return ResourceManager.GetString("SettingsThemeSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-read (disabled in settings) ähnelt.
        /// </summary>
        public static string ArticleAutoMarkReadDisabled {
            get {
                return ResourceManager.GetString("ArticleAutoMarkReadDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-read ({0} s) ähnelt.
        /// </summary>
        public static string ArticleAutoMarkReadDelayFormat {
            get {
                return ResourceManager.GetString("ArticleAutoMarkReadDelayFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove keyword {0} ähnelt.
        /// </summary>
        public static string SettingsKeywordRemoveFormat {
            get {
                return ResourceManager.GetString("SettingsKeywordRemoveFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications ähnelt.
        /// </summary>
        public static string FeedNotificationsLabel {
            get {
                return ResourceManager.GetString("FeedNotificationsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notify about new articles from this feed (requires notifications enabled in the settings) ähnelt.
        /// </summary>
        public static string FeedNotificationsHint {
            get {
                return ResourceManager.GetString("FeedNotificationsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary notification ähnelt.
        /// </summary>
        public static string SettingsNotificationSummaryLabel {
            get {
                return ResourceManager.GetString("SettingsNotificationSummaryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One notification per feed instead of per article ähnelt.
        /// </summary>
        public static string SettingsNotificationSummaryHint {
            get {
                return ResourceManager.GetString("SettingsNotificationSummaryHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} new articles: {1} ähnelt.
        /// </summary>
        public static string NotificationSummaryFormat {
            get {
                return ResourceManager.GetString("NotificationSummaryFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications deactivated ähnelt.
        /// </summary>
        public static string NotificationDeniedTitle {
            get {
                return ResourceManager.GetString("NotificationDeniedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications are deactivated for this app in the system settings. Enable them there to get notified about new articles. ähnelt.
        /// </summary>
        public static string NotificationDeniedMessage {
            get {
                return ResourceManager.GetString("NotificationDeniedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open settings ähnelt.
        /// </summary>
        public static string NotificationDeniedOpenSettings {
            get {
                return ResourceManager.GetString("NotificationDeniedOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications are not allowed yet. Allow them to get notified about new articles. ähnelt.
        /// </summary>
        public static string NotificationNotDeterminedMessage {
            get {
                return ResourceManager.GetString("NotificationNotDeterminedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow notifications ähnelt.
        /// </summary>
        public static string NotificationNotDeterminedAllow {
            get {
                return ResourceManager.GetString("NotificationNotDeterminedAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications are currently only available on iOS. ähnelt.
        /// </summary>
        public static string NotificationsIosOnlyHint {
            get {
                return ResourceManager.GetString("NotificationsIosOnlyHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Article ähnelt.
        /// </summary>
        public static string ArticleTitleFallback {
            get {
                return ResourceManager.GetString("ArticleTitleFallback", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read ähnelt.
        /// </summary>
        public static string ArticleReadLabel {
            get {
                return ResourceManager.GetString("ArticleReadLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full article available ähnelt.
        /// </summary>
        public static string ArticleFullContentAvailable {
            get {
                return ResourceManager.GetString("ArticleFullContentAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in browser ähnelt.
        /// </summary>
        public static string ArticleOpenInBrowser {
            get {
                return ResourceManager.GetString("ArticleOpenInBrowser", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string AccessibilityBack {
            get {
                return ResourceManager.GetString("AccessibilityBack", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle font size ähnelt.
        /// </summary>
        public static string AccessibilityFontSize {
            get {
                return ResourceManager.GetString("AccessibilityFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share ähnelt.
        /// </summary>
        public static string AccessibilityShare {
            get {
                return ResourceManager.GetString("AccessibilityShare", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add bookmark ähnelt.
        /// </summary>
        public static string ArticleBookmarkSet {
            get {
                return ResourceManager.GetString("ArticleBookmarkSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove bookmark ähnelt.
        /// </summary>
        public static string ArticleBookmarkRemove {
            get {
                return ResourceManager.GetString("ArticleBookmarkRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark as read ähnelt.
        /// </summary>
        public static string ArticleMarkAsRead {
            get {
                return ResourceManager.GetString("ArticleMarkAsRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already read ähnelt.
        /// </summary>
        public static string ArticleAlreadyRead {
            get {
                return ResourceManager.GetString("ArticleAlreadyRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} min read ähnelt.
        /// </summary>
        public static string ArticleReadingTimeFormat {
            get {
                return ResourceManager.GetString("ArticleReadingTimeFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Links are disabled while you are offline. ähnelt.
        /// </summary>
        public static string ArticleOfflineLinksDisabled {
            get {
                return ResourceManager.GetString("ArticleOfflineLinksDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No internet connection. ähnelt.
        /// </summary>
        public static string OfflineHint {
            get {
                return ResourceManager.GetString("OfflineHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The category name cannot be empty. ähnelt.
        /// </summary>
        public static string ErrorCategoryNameEmpty {
            get {
                return ResourceManager.GetString("ErrorCategoryNameEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A category with this name already exists. ähnelt.
        /// </summary>
        public static string ErrorCategoryDuplicate {
            get {
                return ResourceManager.GetString("ErrorCategoryDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The link could not be opened in the browser. ähnelt.
        /// </summary>
        public static string ErrorOpenInBrowserFailed {
            get {
                return ResourceManager.GetString("ErrorOpenInBrowserFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The articles could not be loaded. ähnelt.
        /// </summary>
        public static string ErrorLoadFailed {
            get {
                return ResourceManager.GetString("ErrorLoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feed URL or website address… ähnelt.
        /// </summary>
        public static string PlaceholderFeedSearch {
            get {
                return ResourceManager.GetString("PlaceholderFeedSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No feeds found. ähnelt.
        /// </summary>
        public static string FeedSearchNoResults {
            get {
                return ResourceManager.GetString("FeedSearchNoResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No feed found ähnelt.
        /// </summary>
        public static string FeedSearchNoResultsTitle {
            get {
                return ResourceManager.GetString("FeedSearchNoResultsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No feed found. Do you want to add &quot;{0}&quot; directly? ähnelt.
        /// </summary>
        public static string FeedSearchNoResultsAddUrl {
            get {
                return ResourceManager.GetString("FeedSearchNoResultsAddUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feed search is unavailable. You can add the URL directly. ähnelt.
        /// </summary>
        public static string FeedSearchUnavailable {
            get {
                return ResourceManager.GetString("FeedSearchUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feed search is unavailable. Please try again later or enter a complete feed URL. ähnelt.
        /// </summary>
        public static string FeedSearchUnavailableRetry {
            get {
                return ResourceManager.GetString("FeedSearchUnavailableRetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feed search is not available offline — you can still add a URL directly. ähnelt.
        /// </summary>
        public static string FeedSearchOfflineHint {
            get {
                return ResourceManager.GetString("FeedSearchOfflineHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search powered by feedsearch.dev ähnelt.
        /// </summary>
        public static string FeedSearchAttribution {
            get {
                return ResourceManager.GetString("FeedSearchAttribution", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subscribe to feed? ähnelt.
        /// </summary>
        public static string ConfirmSubscribeFeedTitle {
            get {
                return ResourceManager.GetString("ConfirmSubscribeFeedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subscribe to &quot;{0}&quot;? ähnelt.
        /// </summary>
        public static string ConfirmSubscribeFeedMessage {
            get {
                return ResourceManager.GetString("ConfirmSubscribeFeedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to my feeds ähnelt.
        /// </summary>
        public static string ButtonCloseSearchResults {
            get {
                return ResourceManager.GetString("ButtonCloseSearchResults", resourceCulture);
            }
        }
    }
}
