//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporter.Core.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporter.Core.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category actions ähnelt.
        /// </summary>
        public static string ActionSheetTitleCategory {
            get {
                return ResourceManager.GetString("ActionSheetTitleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feed actions ähnelt.
        /// </summary>
        public static string ActionSheetTitleFeed {
            get {
                return ResourceManager.GetString("ActionSheetTitleFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string ButtonRefresh {
            get {
                return ResourceManager.GetString("ButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh all ähnelt.
        /// </summary>
        public static string ButtonRefreshAll {
            get {
                return ResourceManager.GetString("ButtonRefreshAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die — ähnelt.
        /// </summary>
        public static string CategoryNone {
            get {
                return ResourceManager.GetString("CategoryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All articles belonging to this feed will also be deleted. Continue? ähnelt.
        /// </summary>
        public static string ConfirmDeleteFeedMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteFeedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete feed? ähnelt.
        /// </summary>
        public static string ConfirmDeleteFeedTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A feed with this URL already exists. ähnelt.
        /// </summary>
        public static string ErrorFeedDuplicate {
            get {
                return ResourceManager.GetString("ErrorFeedDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a display title. ähnelt.
        /// </summary>
        public static string ErrorFeedTitleEmpty {
            get {
                return ResourceManager.GetString("ErrorFeedTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid feed URL. ähnelt.
        /// </summary>
        public static string ErrorFeedUrlInvalid {
            get {
                return ResourceManager.GetString("ErrorFeedUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string HealthStatusErrorLabel {
            get {
                return ResourceManager.GetString("HealthStatusErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string HealthStatusOkLabel {
            get {
                return ResourceManager.GetString("HealthStatusOkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string HealthStatusWarningLabel {
            get {
                return ResourceManager.GetString("HealthStatusWarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feeds ähnelt.
        /// </summary>
        public static string LabelCategoryFeedCount {
            get {
                return ResourceManager.GetString("LabelCategoryFeedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string LabelCategoryName {
            get {
                return ResourceManager.GetString("LabelCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string LabelFeedActions {
            get {
                return ResourceManager.GetString("LabelFeedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string LabelFeedCategory {
            get {
                return ResourceManager.GetString("LabelFeedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Health ähnelt.
        /// </summary>
        public static string LabelFeedHealthStatus {
            get {
                return ResourceManager.GetString("LabelFeedHealthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last check ähnelt.
        /// </summary>
        public static string LabelFeedLastCheck {
            get {
                return ResourceManager.GetString("LabelFeedLastCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string LabelFeedTitle {
            get {
                return ResourceManager.GetString("LabelFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unread ähnelt.
        /// </summary>
        public static string LabelFeedUnreadCount {
            get {
                return ResourceManager.GetString("LabelFeedUnreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No items ähnelt.
        /// </summary>
        public static string LabelNoItems {
            get {
                return ResourceManager.GetString("LabelNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        public static string PageTitleCategories {
            get {
                return ResourceManager.GetString("PageTitleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feeds ähnelt.
        /// </summary>
        public static string PageTitleFeeds {
            get {
                return ResourceManager.GetString("PageTitleFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Later ähnelt.
        /// </summary>
        public static string PageTitleLater {
            get {
                return ResourceManager.GetString("PageTitleLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unread ähnelt.
        /// </summary>
        public static string PageTitleUnread {
            get {
                return ResourceManager.GetString("PageTitleUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories will appear here. ähnelt.
        /// </summary>
        public static string PlaceholderCategories {
            get {
                return ResourceManager.GetString("PlaceholderCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feeds will appear here. ähnelt.
        /// </summary>
        public static string PlaceholderFeeds {
            get {
                return ResourceManager.GetString("PlaceholderFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display title ähnelt.
        /// </summary>
        public static string PlaceholderFeedTitle {
            get {
                return ResourceManager.GetString("PlaceholderFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://example.com/feed ähnelt.
        /// </summary>
        public static string PlaceholderFeedUrl {
            get {
                return ResourceManager.GetString("PlaceholderFeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Articles you save for later will appear here. ähnelt.
        /// </summary>
        public static string PlaceholderLater {
            get {
                return ResourceManager.GetString("PlaceholderLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings will appear here. ähnelt.
        /// </summary>
        public static string PlaceholderSettings {
            get {
                return ResourceManager.GetString("PlaceholderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unread articles will appear here. ähnelt.
        /// </summary>
        public static string PlaceholderUnread {
            get {
                return ResourceManager.GetString("PlaceholderUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronization failed. ähnelt.
        /// </summary>
        public static string SyncStatusError {
            get {
                return ResourceManager.GetString("SyncStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        public static string TabCategories {
            get {
                return ResourceManager.GetString("TabCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feeds ähnelt.
        /// </summary>
        public static string TabFeeds {
            get {
                return ResourceManager.GetString("TabFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Later ähnelt.
        /// </summary>
        public static string TabLater {
            get {
                return ResourceManager.GetString("TabLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unread ähnelt.
        /// </summary>
        public static string TabUnread {
            get {
                return ResourceManager.GetString("TabUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to Reporter. ähnelt.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Article actions ähnelt.
        /// </summary>
        public static string ActionSheetArticle {
            get {
                return ResourceManager.GetString("ActionSheetArticle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bookmark ähnelt.
        /// </summary>
        public static string ButtonBookmark {
            get {
                return ResourceManager.GetString("ButtonBookmark", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All read ähnelt.
        /// </summary>
        public static string ButtonMarkAllRead {
            get {
                return ResourceManager.GetString("ButtonMarkAllRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark as read ähnelt.
        /// </summary>
        public static string ButtonMarkAsRead {
            get {
                return ResourceManager.GetString("ButtonMarkAsRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pull down to refresh ähnelt.
        /// </summary>
        public static string LabelPullToRefresh {
            get {
                return ResourceManager.GetString("LabelPullToRefresh", resourceCulture);
            }
        }
    }
}
