<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>CS1591</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings\AppResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Reporter.Core.Resources.Strings</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings\AppResources.de.resx" />
    <Compile Update="Resources\Strings\AppResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
