// Licensed under the PolyForm Noncommercial License 1.0.0 - see the LICENSE file in the project root for details.

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reporter.Data;

#nullable disable

namespace Reporter.Data.Migrations.Content
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260919084558_AddItemContentImageColumns")]
    partial class AddItemContentImageColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Reporter.Data.Entities.ItemContent", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_id");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_html");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_content_type");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("BLOB")
                        .HasColumnName("image_data");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.HasKey("ItemId");

                    b.ToTable("item_contents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
