// Licensed under the PolyForm Noncommercial License 1.0.0 - see the LICENSE file in the project root for details.

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reporter.Data;

#nullable disable

namespace Reporter.Data.Migrations
{
    [DbContext(typeof(ReporterDbContext))]
    [Migration("20260913211308_AddFeedFaviconUrl")]
    partial class AddFeedFaviconUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Reporter.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Reporter.Data.Entities.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("favicon_url");

                    b.Property<DateTime?>("HealthLastChange")
                        .HasColumnType("TEXT")
                        .HasColumnName("health_last_change");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("health_status");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_checked_at");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("notifications_enabled");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("feeds", (string)null);
                });

            modelBuilder.Entity("Reporter.Data.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_html");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("TEXT")
                        .HasColumnName("feed_id");

                    b.Property<string>("GuidOrHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("guid_or_hash");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_read");

                    b.Property<bool>("IsSavedForLater")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_saved_for_later");

                    b.Property<string>("Link")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("link");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("FeedId", "GuidOrHash")
                        .IsUnique();

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Reporter.Data.Entities.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("KeywordText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("keyword_text");

                    b.HasKey("Id");

                    b.HasIndex("KeywordText")
                        .IsUnique();

                    b.ToTable("keywords", (string)null);
                });

            modelBuilder.Entity("Reporter.Data.Entities.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AutoMarkReadDelaySeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_mark_read_delay_seconds");

                    b.Property<string>("AutoMarkReadMode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("auto_mark_read_mode");

                    b.Property<bool>("AutoRefreshEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_refresh_enabled");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<bool>("NotificationSummaryEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("notification_summary_enabled");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("notifications_enabled");

                    b.Property<TimeSpan?>("QuietHoursEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("quiet_hours_end");

                    b.Property<TimeSpan?>("QuietHoursStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("quiet_hours_start");

                    b.Property<int>("RefreshIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(30)
                        .HasColumnName("refresh_interval_minutes");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retention_days");

                    b.Property<string>("Theme")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("theme");

                    b.HasKey("Id");

                    b.ToTable("settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f5c6d2-4b3e-4c8f-9d2a-1b2c3d4e5f6a"),
                            AutoMarkReadDelaySeconds = 5,
                            AutoMarkReadMode = "on_scroll",
                            AutoRefreshEnabled = true,
                            Language = "system",
                            NotificationSummaryEnabled = false,
                            NotificationsEnabled = true,
                            RefreshIntervalMinutes = 30,
                            RetentionDays = 30,
                            Theme = "system"
                        });
                });

            modelBuilder.Entity("Reporter.Data.Entities.SyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("FeedId")
                        .HasColumnType("TEXT")
                        .HasColumnName("feed_id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FeedId");

                    b.ToTable("sync_logs", (string)null);
                });

            modelBuilder.Entity("Reporter.Data.Entities.Feed", b =>
                {
                    b.HasOne("Reporter.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Reporter.Data.Entities.Item", b =>
                {
                    b.HasOne("Reporter.Data.Entities.Feed", "Feed")
                        .WithMany()
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("Reporter.Data.Entities.SyncLog", b =>
                {
                    b.HasOne("Reporter.Data.Entities.Feed", "Feed")
                        .WithMany()
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Feed");
                });
#pragma warning restore 612, 618
        }
    }
}
